project:
  output-dir: docs
  resources:
    - favicon.png

format:
  html:
    theme: [cosmo, report.scss]
    toc: true
    number-sections: true
    code-fold: true
    embed-resources: true
    favicon: "favicon.png"